<a href="https://colab.research.google.com/github/shreevaishnavim/Neural-network-and-deep-learning/blob/main/NNDL_ASSINGMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NNDl Assignment

1. What is the syntax for creating a tensor.

In [ ]:
The syntax varies by framework:

PyTorch: torch.tensor(data) or factory functions like torch.zeros(), torch.ones(), torch.randn()

TensorFlow: tf.constant(data) or tf.Variable(data)

NumPy: np.array(data) (technically arrays, not tensors with gradients)

Key Components:

Data (list, array, or scalar)

Optional: dtype, device (CPU/GPU), requires_grad (PyTorch)

2. what are the different tensor operations



In [ ]:
Tensor operations can be categorized as:

1.Creation Operations:

zeros(), ones(), randn(), arange(), linspace()

2.Mathematical Operations:

Element-wise: +, -, *, /, exp(), log()

3.Matrix operations: matmul(), dot(), transpose()

Reduction: sum(), mean(), max(), min()

4.Shape Operations:

reshape(), view(), permute(), squeeze(), unsqueeze()

5.Indexing & Slicing:

tensor[i, j], tensor[:, 2:5], masked_select()

6.Statistical Operations:

std(), var(), norm(), argmax()



3.Create a 2×3 tensor filled with zeros and another filled with ones.



In [ ]:
import torch

# Create 2x3 tensor filled with zeros
zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor:\n", zeros_tensor)

# Create 2x3 tensor filled with ones
ones_tensor = torch.ones(2, 3)
print("\nOnes Tensor:\n", ones_tensor)

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


4.Convert a Python list [[1,2,3],[4,5,6]] into a tensor and print its shape and data type.

In [ ]:
import torch

# Python list
python_list = [[1, 2, 3], [4, 5, 6]]

# Convert to tensor
tensor_from_list = torch.tensor(python_list)

# Print tensor
print("Tensor:\n", tensor_from_list)
print("\nShape:", tensor_from_list.shape)
print("Data type:", tensor_from_list.dtype)
print("Dimensions:", tensor_from_list.ndim)

Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Shape: torch.Size([2, 3])
Data type: torch.int64
Dimensions: 2


5.Reshape a tensor of size 12 into shape (3,4).

In [ ]:
import torch

# Create tensor of size 12
original_tensor = torch.arange(12)  # or torch.tensor([...]) with 12 elements
print("Original Tensor (size 12):\n", original_tensor)

# Reshape to (3, 4)
reshaped_tensor = original_tensor.reshape(3, 4)
print("\nReshaped Tensor (3x4):\n", reshaped_tensor)

# Alternative: view() but only works on contiguous tensors
# reshaped_tensor = original_tensor.view(3, 4)

Original Tensor (size 12):
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped Tensor (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


6.Find the rank (number of dimensions) of a given tensor.



In [ ]:
import torch

# Create tensors with different dimensions
tensor_1d = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.randn(2, 3, 4)

def get_tensor_rank(tensor):
    return tensor.ndim  # or len(tensor.shape)

print("1D Tensor rank:", get_tensor_rank(tensor_1d))
print("2D Tensor rank:", get_tensor_rank(tensor_2d))
print("3D Tensor rank:", get_tensor_rank(tensor_3d))

1D Tensor rank: 1
2D Tensor rank: 2
3D Tensor rank: 3


7.Extract the second row and third column from a 2D tensor.



In [ ]:
import torch

# Create a 2D tensor
tensor_2d = torch.tensor([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

print("Original Tensor (3x4):\n", tensor_2d)

# Extract second row (index 1)
second_row = tensor_2d[1, :]
print("\nSecond Row:", second_row)

# Extract third column (index 2)
third_column = tensor_2d[:, 2]
print("Third Column:", third_column)

# Extract element at second row, third column
element = tensor_2d[1, 2]
print("Element at [1, 2]:", element.item())

Original Tensor (3x4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Second Row: tensor([5, 6, 7, 8])
Third Column: tensor([ 3,  7, 11])
Element at [1, 2]: 7


8.Compute matrix multiplication between tensors of shape (3,4) and (4,2).



In [ ]:
import torch

# Create tensors
tensor_A = torch.randn(3, 4)  # Shape (3, 4)
tensor_B = torch.randn(4, 2)  # Shape (4, 2)

print("Tensor A (3x4):\n", tensor_A)
print("\nTensor B (4x2):\n", tensor_B)

# Matrix multiplication
# Method 1: torch.matmul()
result_matmul = torch.matmul(tensor_A, tensor_B)
print("\nResult using matmul() (3x2):\n", result_matmul)

# Method 2: @ operator
result_operator = tensor_A @ tensor_B
print("\nResult using @ operator (3x2):\n", result_operator)

# Method 3: torch.mm() (only for 2D tensors)
result_mm = torch.mm(tensor_A, tensor_B)
print("\nResult using mm() (3x2):\n", result_mm)

print("\nAll methods equal:", torch.allclose(result_matmul, result_operator) and
      torch.allclose(result_matmul, result_mm))

Tensor A (3x4):
 tensor([[-0.8276, -0.8448, -0.0446, -0.7563],
        [-2.1690, -0.1137, -0.0366,  1.0872],
        [-0.3652, -1.5170,  1.2771, -1.2534]])

Tensor B (4x2):
 tensor([[ 0.5524,  1.3845],
        [-0.5727,  0.4409],
        [ 1.1816, -0.2304],
        [ 0.8729,  0.2918]])

Result using matmul() (3x2):
 tensor([[-0.6862, -1.7288],
        [-0.2273, -2.7275],
        [ 1.0818, -1.8345]])

Result using @ operator (3x2):
 tensor([[-0.6862, -1.7288],
        [-0.2273, -2.7275],
        [ 1.0818, -1.8345]])

Result using mm() (3x2):
 tensor([[-0.6862, -1.7288],
        [-0.2273, -2.7275],
        [ 1.0818, -1.8345]])

All methods equal: True


9.Find the transpose of a 3D tensor.



In [9]:
import torch

# Create a 3D tensor (example: 2 batches, 3 rows, 4 columns)
tensor_3d = torch.tensor([
    [[1, 2, 3, 4],   # Batch 0, Row 0
     [5, 6, 7, 8],   # Batch 0, Row 1
     [9, 10, 11, 12]], # Batch 0, Row 2

    [[13, 14, 15, 16],  # Batch 1, Row 0
     [17, 18, 19, 20],  # Batch 1, Row 1
     [21, 22, 23, 24]]  # Batch 1, Row 2
])

print("Original 3D Tensor shape:", tensor_3d.shape)  # (2, 3, 4)
print("Original tensor:\n", tensor_3d)

# Method 1: Transpose specific dimensions (swap dimensions 1 and 2)
transposed = tensor_3d.transpose(1, 2)  # Swap rows and columns
print("\nTransposed (swap dims 1&2) shape:", transposed.shape)  # (2, 4, 3)
print("Transposed tensor:\n", transposed)

# Method 2: Using permute for any dimension order
permuted = tensor_3d.permute(0, 2, 1)  # Equivalent to transpose(1, 2)
print("\nPermuted shape:", permuted.shape)

# Method 3: Transpose each 2D matrix individually
print("\nTransposing each 2D slice individually:")
for i in range(tensor_3d.shape[0]):
    print(f"\nBatch {i} original:\n", tensor_3d[i])
    print(f"Batch {i} transposed:\n", tensor_3d[i].T)  # .T works for 2D tensors

Original 3D Tensor shape: torch.Size([2, 3, 4])
Original tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

Transposed (swap dims 1&2) shape: torch.Size([2, 4, 3])
Transposed tensor:
 tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])

Permuted shape: torch.Size([2, 4, 3])

Transposing each 2D slice individually:

Batch 0 original:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Batch 0 transposed:
 tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

Batch 1 original:
 tensor([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])
Batch 1 transposed:
 tensor([[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]])


10.Implement softmax using tensor operations (no built-in function).



In [13]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

#Simple array
print("Simple array")
x1 = np.array([1.0, 2.0, 3.0])
result1 = softmax(x1)
print(f"Input: {x1}")
print(f"Output: {result1}")
print(f"Sum: {np.sum(result1):.6f}")  # Should sum to 1
print()

Simple array
Input: [1. 2. 3.]
Output: [0.09003057 0.24472847 0.66524096]
Sum: 1.000000



11.Normalize a tensor so that values lie between 0 and 1.



In [16]:
import numpy as np

# 2-mark solution
def normalize(tensor):
    return (tensor - tensor.min()) / (tensor.max() - tensor.min())

# Test and print
x = np.array([10, 20, 30, 40, 50])
result = normalize(x)

print("Input tensor:", x)
print("Normalized:", result)
print("Min value:", result.min())
print("Max value:", result.max())

Input tensor: [10 20 30 40 50]
Normalized: [0.   0.25 0.5  0.75 1.  ]
Min value: 0.0
Max value: 1.0


12.Write code to compute gradients of a tensor operation (PyTorch).

In [17]:
import torch

# Create a tensor with requires_grad=True for gradient computation
x = torch.tensor([2.0], requires_grad=True)

# Define an operation: y = x^2 + 3x + 1
y = x**2 + 3*x + 1

# Compute gradients
y.backward()

# Print results
print("x =", x.item())
print("y = x² + 3x + 1 =", y.item())
print("Gradient dy/dx =", x.grad.item())
print("Analytical derivative: 2x + 3 =", 2*x.item() + 3)

x = 2.0
y = x² + 3x + 1 = 11.0
Gradient dy/dx = 7.0
Analytical derivative: 2x + 3 = 7.0


13.Convert an image tensor (H, W, C) to (C, H, W).

In [18]:
import torch

# Create a random image tensor: (Height, Width, Channels)
# Simulating a 4x3 RGB image
image_hwc = torch.randn(4, 3, 3)  # H=4, W=3, C=3
print("Original shape (H, W, C):", image_hwc.shape)

# Convert to (C, H, W) using permute
image_chw = image_hwc.permute(2, 0, 1)
print("Converted shape (C, H, W):", image_chw.shape)
print()

# Alternative method using .permute
print("Using permute(2, 0, 1):")
print("Input shape:", image_hwc.shape)
print("Output shape:", image_hwc.permute(2, 0, 1).shape)

Original shape (H, W, C): torch.Size([4, 3, 3])
Converted shape (C, H, W): torch.Size([3, 4, 3])

Using permute(2, 0, 1):
Input shape: torch.Size([4, 3, 3])
Output shape: torch.Size([3, 4, 3])


14.Mask elements in a tensor based on a condition.

In [19]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

# Mask elements greater than 4
mask = tensor > 4
masked_tensor = tensor * mask

print("Original tensor:")
print(tensor)
print("\nMask (values > 4):")
print(mask)
print("\nMasked tensor (keeps values > 4, others become 0):")
print(masked_tensor)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Mask (values > 4):
tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

Masked tensor (keeps values > 4, others become 0):
tensor([[0, 0, 0],
        [0, 5, 6],
        [7, 8, 9]])


15.Difference between view, reshape, and transpose in tensors.



In [ ]:
view(): Changes shape without copying data (memory efficient). Requires tensor to be contiguous.

reshape(): Changes shape may copy data if needed. Works on both contiguous/non-contiguous tensors.

transpose(): Swaps dimensions (e.g., rows ↔ columns). Changes stride pattern, not memory layout.



16.What is contiguous memory in tensor operations?



In [ ]:
Contiguous memory means tensor elements are stored sequentially in memory without gaps. Operations on contiguous tensors are faster because they enable:

1.Better cache utilization

2.Vectorized operations (SIMD)

3.Direct memory access patterns
Example: [1,2,3,4,5] is contiguous; [[1,2],[3,4]] after transpose may not be.



17.Why is broadcasting efficient?



In [ ]:
Broadcasting avoids actual data duplication. Instead of copying data to match shapes:

1.Uses stride tricks to virtually repeat data

2.Reduces memory usage

3.Enables vectorized operations
Example: Adding [1,2,3] to each row of matrix uses same 3 values without copying.



18.Explain tensor vs matrix vs vector with examples.



In [ ]:
Vector: 1D array [1, 2, 3] (magnitude + direction)

Matrix: 2D array [[1,2],[3,4]] (linear transformations)

Tensor: N-D array (generalization) - can be 3D [batch, height, width], 4D [batch, channels, height, width], etc.



19.How do tensor operations enable GPU acceleration?



In [ ]:
Parallelizable - Same operation on all elements

Batch operations - Process multiple data points simultaneously

Memory coalesced - Aligned memory access patterns
GPUs have thousands of cores that can execute these parallel operations simultaneously.




20.Implement cosine similarity using tensor operations.



In [20]:
import torch

def cosine_similarity(a, b):
    # Normalize vectors
    a_norm = a / torch.norm(a)
    b_norm = b / torch.norm(b)
    # Dot product
    return torch.dot(a_norm, b_norm)

# Test
v1 = torch.tensor([1.0, 2.0, 3.0])
v2 = torch.tensor([4.0, 5.0, 6.0])
print("Cosine similarity:", cosine_similarity(v1, v2).item())

Cosine similarity: 0.9746317863464355
